### PR TITLE
added ci that downloads materials theme

### PR DESCRIPTION
**Pull request by raghavauppuluri13**
The theme may not have been downloading during the deployment, maybe this ci workflow can help?﻿

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Thanks @raghavauppuluri13! Let's give it a go and see

**Comment by Tobias-Fischer** [comment]
How is that going to work with the tables? I guess we need to modify that action to rebuild using mkdocs as well?

**Comment by raghavauppuluri13** [comment]
I just added another commit that has the deploy workflow added as another job in the update tables workflow. Would that work?

**Comment by Tobias-Fischer** [comment]
Let's try this - it should trigger the other job if tables are updated: https://github.com/RoboStack/robostack.github.io/commit/e5ed7b4d20b59cf1c0afcdbdb56e62718c14c229

**Comment by Tobias-Fischer** [comment]
Actually there is no need for https://github.com/RoboStack/robostack.github.io/commit/e5ed7b4d20b59cf1c0afcdbdb56e62718c14c229 - the update tables push to the main branch and that leads to a rebuild anyhow :)

**Pull request merged**
