### PR TITLE
Create update-package-table.yml

### PR DESCRIPTION
**Pull request by Tobias-Fischer**

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - it would be great if you could check this PR. I guess we should setup a separate branch where the changes are written to, and force-pushed to. What do you think?

**Comment by wolfv** [comment]
I think this might be fine if we do it every ~6 hours so that we can do manual changes in between? Otherwise, it might be annoying quite soon?!
We could also move the python script to this repo here -- and add `foxy`?

**Comment by Tobias-Fischer** [comment]
Hi @wolfv - I did some modifications, what do you think?

**Comment by Tobias-Fischer** [comment]
Hmm for some reason the formatting has gone off. Any idea why @wolfv?

**Pull request merged**
