### PR TITLE
WIP: Use mkdocs for RoboStack

### PR DESCRIPTION
**Pull request by ooeygui**
I've started working on updating the landing pages for RoboStack. I manually updated the tables for formatting, I'll update the pull request with that fix.

I wanted to start the PR to get feedback on the theme, layout and content.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
Hi @ooeygui,

This looks great to me, many thanks! I'd be very happy for this to be used. Some small tweaks needed here and there, but overall it's very nice. What do you think @wolfv @traversaro?

**Comment by wolfv** [comment]
cool! Just FYI the tables are auto-generated every ~6 hours by a github action. Is that still the case with this PR?

**Comment by ooeygui** [comment]
I'm working on updating the script to generate the markdown tables; I did this manually to see how well it worked within the theme.

**Comment by ooeygui** [comment]
I updated the script to generate markdown tables.

**Comment by Tobias-Fischer** [comment]
I made some minor tweaks and enabled sorting of the package tables .. I'd be happy to merge as is ;)

**Comment by wolfv** [comment]
alright let's see what happens! :)

**Comment by wolfv** [comment]
I merged this but there seem to be two minor issues:

- tables show :checkmark: and similar markup. not sure where that comes from
- it seems like we don't get a navigation yet. I am not sure how mkdocs works but maybe we're getting teh wrong index.html by pointing at the docs folder? But there was no index.html generated in the root folder. 

Any ideas @ooeygui? If you don't I can have a deeper look :) Thanks a ton for this work!

https://robostack.github.io/

**Comment by wolfv** [comment]
PS I gave you maintainer rights on this repo so you should be free to push any changes right away

**Comment by Tobias-Fischer** [comment]
I think we're missing https://github.com/marketplace/actions/deploy-mkdocs

**Pull request merged**
